### PR TITLE
Code formatting

### PR DESCRIPTION
**Pull request by Zeus64**

### CODE REVIEW

**Comment by davidham2020** [comment]
Dear Zeus64,
I'm sorry to bother you! I want to ask you a question about how to use the AndroidMerger tool that comes with alcinoe! Could you send a youtube video to demonstrate the usage and precautions, such as how to determine the dependencies of an sdk, etc., thank you so much!

**Comment by Zeus64** [comment]
Hi, yes sure I will try to make a video, but I just miss the time for this :( I think the help I made on androidmerger is quite helpfull ( https://github.com/MagicFoundation/Alcinoe/blob/master/Tools/AndroidMerger/Readme.md ). their is a working example of how to build such batch here: https://github.com/MagicFoundation/Alcinoe/blob/master/Demos/ALFmxControls/_Source/android/MergeLibraries.bat

**Comment by davidham2020** [comment]
Thank you sincerely for your answer! Let me try it first. I look forward to your wonderful video. Thank you again!

**Comment by davidham2020** [comment]
Dear Zeus64,
I'm sorry to bother you again!According to your suggestion, after using the Android Merge tool, I was prompted to complete the merge, but no local bridge file was generated. I need to use the bridge file to perform the corresponding operation. Could you help me solve this question?thank you so much!

**Comment by Zeus64** [comment]
Hi david, what you mean by local bridge file ?

**Comment by davidham2020** [comment]
Dear Zeus64,
  The sentence "Generate the Delphi native bridge file from the Java libraries." in line 15, column 2 of  (https://github.com/MagicFoundation/Alcinoe/blob/master/Tools/AndroidMerger/Readme.md) And I found in the source code that it was implemented using the java2op.exe, but I did not find the generated Delphi native bridge file.

**Comment by davidham2020** [comment]
Dear Zeus64,
I was too careless to add the "GenerateNativeBridgeFile" parameter. Now that the problem has been resolved, thank you very much for your help!
In addition, I would also like to ask you a question: How does the ALVideoPlayerSurface component play local multimedia files?

**Comment by davidham2020** [comment]
Dear Zeus64,
I would like to ask you how to determine the value of the "- Libraries=" parameter, such as "com. google. android. exolayer: exolayer core: 2.18.2" in "- Libraries=com. google. android. exolayer: exolayer core: 2.18.2". How did it come from?

**Comment by Zeus64** [comment]
Hi, i took it from https://maven.google.com/web/index.html

**Comment by davidham2020** [comment]
thanks a lot.

**Comment by davidham2020** [comment]
thanks a lot.

**Pull request merged**
